name: EC2-ubuntu
on:
  push:
    branches: ['develop']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.PEM_KEY }}" > ~/jaedoo.pem
          chmod 600 ~/jaedoo.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PUBLIC_DNS }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/jaedoo.pem haemin@${{ secrets.PUBLIC_DNS }}
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker ps
          
          
           
