name: EC2-ubuntu
on :
  push:
    branches: ['develop']
permissions :
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ssh
        run: |
          echo "${{secrets.PEM_KEY}}" > ~/jaedoo.pem
          chmod 400 ~/jaedoo.pem

      - name: make .ssh dir
        run: |
          mkdir -p ~/.ssh

      - name: key add
        run: |
          ssh-keyscan -H ${{ secrets.PUBLIC_DNS }} >> ~/.ssh/known_hosts

      - name: Pipe-line
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/jaedoo.pem haemin@${{ secrets.PUBLIC_DNS }} 'ls'
          
          
