name: EC2-ubuntu
on:
  push:
    branches: ['develop']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.PEM_KEY }}" > ~/jaedoo.pem
          chmod 600 ~/jaedoo.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PUBLIC_DNS }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/jaedoo.pem haemin@${{ secrets.PUBLIC_DNS }} << 'EOF'
            echo "Logging in to Docker..."
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
            # 기존 컨테이너가 있으면 중지하고 제거
            if [ "$(docker ps -q -f name=qr-order-web-container)" ]; then
              echo "Stopping and removing existing container..."
              docker stop qr-order-web-container
              docker rm qr-order-web-container
            fi
          
            echo "Pulling the latest image..."
            docker pull ghcr.io/foopery/qr-order-web/qr-order-web:latest
          
            echo "Starting new container..."
            docker run -d --name qr-order-web-container -p 80:80 ghcr.io/foopery/qr-order-web/qr-order-web:latest
          
            echo "Current running containers:"
            docker ps
          EOF
