name: EC2-ubuntu
on :
  push:
    branches: ['develop']
permissions :
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ssh
        run: |
          echo "${{secrets.PEM_KEY}}" > ~/jaedoo.pem
          chmod 400 ~/jaedoo.pem

      - name: Pipe-line
        run: |
          ssh -i ~/jaedoo.pem haemin@${{secrets.PUBLIC_DNS}} 'ls'
          
          
