name: EC2-ubuntu
on:
  push:
    branches: ['develop']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pipe-line
        run: |
          echo "${{ secrets.PEM_KEY }}" > ~/jaedoo.pem
          chmod 600 ~/jaedoo.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PUBLIC_DNS }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/jaedoo.pem ubuntu@${{ secrets.PUBLIC_DNS }} 'ls'
