name : qr-order-web
on :
  push:
    branches: ['develop']
permissions :
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker Build
        uses: docker/setup-buildx-action@v1

      - name: build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}/qr-order-web:latest

      - name: Logout Container Registry
        run: docker logout ghcr.io





