name: test-prac
on :
  push:
    branches: ['develop']
permissions :
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: mkdir/cd
        run: |
          cd /home/runner/work/qr-order-web/qr-order-web
          mkdir -p GGG
          cd GGG
          echo "inhanbyeol94@gmail.com" > abcd.txt
          export JAEDOO=$(cat abcd.txt)
          echo $JAEDOO
          


