name: test-prac
on :
  push:
    branches: ['develop']
permissions :
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cd
        run: cd /home/runner/work/qr-order-web/qr-order-web

      - name: create mkdir
        run: mkdir -p /home/runner/work/qr-order-web/qr-order-web/GGG

      - name: mkdir/cd
        run: cd /home/runner/work/qr-order-web/qr-order-web/GGG
             pwd


